name: 'build and deploy production'

on:
  push:
    tags:
      - 'v1000'

jobs:
  build-production-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Set nodejs version to 18.x 
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
    
      - run: npm ci
    
      - name: run  build production( create dist floder)
        run: npm run build
    
      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist-production
          path: dist

  deploy-production-job:
    needs: build-production-job
    runs-on: ubuntu-latest
    steps:
      - name: Download dist floder artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-production
          path: dist
      - run: ls 

      - uses: actions/checkout@v4

      - name: publsh vue to github pages
        uses: SerhiiKa/VuePagesAction@1.0.4
        with:
          username: ${{ github.actor }}   # somchai-fitm
          reponame: ${{github.event.repository.name }}  # vue-github-app
          token: ${{ secrets.GITHUB_TOKEN }}