name: 'build and deploy production'

on:
  push:
    tags:
      - '*'

jobs:
  build-production-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    
      - name: Set nodejs version to 18.x 
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
    
      - run: npm ci
    
      - name: run  build production( create dist floder)
        run: npm run build
    