name: 'CI'

on:
  push:
    branches:
      - main

jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set nodejs version to 18.x 
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - run: npm ci

      - name: run lint
        run: npm run lint

      - name: run format
        run: npm run format

  unit-test-job:
    runs-on: ubuntu-latest
    needs: lint-job
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v4
        
      - name:  nodejs version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        
      - run: npm ci
        
      - name: run unit test
        run: npm run test:unit
        